name: GCD Script Manual Test

on:
  workflow_dispatch:

  push:
    paths:
      - 'calc_gcd.sh'
      - 'test_calc_gcd.sh'
  pull_request:
    paths:
      - 'calc_gcd.sh'
      - 'test_calc_gcd.sh'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Make scripts executable
        run: chmod +x calc_gcd.sh test_calc_gcd.sh

      - name: Run test suite
        run: ./test_calc_gcd.sh
